import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexHtml = readFileSync(resolve(__dirname, '..', 'index.html'), 'utf8');
const appJs = readFileSync(resolve(__dirname, '..', 'app.js'), 'utf8');
const stylesCss = readFileSync(resolve(__dirname, '..', 'styles.css'), 'utf8');
const viJs = readFileSync(resolve(__dirname, '..', 'i18n', 'vi.js'), 'utf8');
const enJs = readFileSync(resolve(__dirname, '..', 'i18n', 'en.js'), 'utf8');
const continuePrintBlock = appJs.match(/async _continuePrint\(\)\s*\{[\s\S]*?\n    async _completeCurrentManualJob/)?.[0] ?? '';

assert.match(indexHtml, /<div class="print-actions"[^>]*>/);
assert.match(indexHtml, /<div class="print-actions"[\s\S]*id="recovery-btn"[\s\S]*id="print-btn"[\s\S]*<\/div>/);
assert.match(indexHtml, /id="recovery-job-select"/);
assert.doesNotMatch(indexHtml, /id="complete-print-btn"/);
assert.doesNotMatch(indexHtml, /id="recovery-btn"[^>]*(hidden|class="[^"]*\bhidden\b)/);
assert.match(stylesCss, /\.print-actions\s*{[\s\S]*display:\s*flex;/);
assert.match(stylesCss, /\.print-actions\s*{[\s\S]*position:\s*relative;/);
assert.match(stylesCss, /\.print-actions\s+\.btn-print[\s\S]*flex:\s*0 0 auto;/);
assert.match(stylesCss, /\.print-actions\s+\.btn-recovery[\s\S]*flex:\s*0 0 auto;/);
assert.match(stylesCss, /\.btn-recovery:disabled/);
assert.doesNotMatch(stylesCss, /completePrintPulse/);
assert.doesNotMatch(stylesCss, /\.btn-complete-print/);

assert.match(indexHtml, /id="flip-cancel-print-btn"/);
assert.match(indexHtml, /id="phase1-recovery-open-btn"[\s\S]*id="flip-cancel-print-btn"[\s\S]*id="continue-btn"/);
assert.doesNotMatch(indexHtml, /id="flip-timer-enable"/);
assert.doesNotMatch(indexHtml, /id="flip-timer-bar"/);
assert.doesNotMatch(indexHtml, /id="flip-timer-fill"/);
assert.doesNotMatch(appJs, /flip-timer-enable/);
assert.doesNotMatch(appJs, /flip-timer-bar/);
assert.doesNotMatch(appJs, /flip-timer-fill/);
assert.doesNotMatch(appJs, /setInterval\(\(\) => \{[\s\S]*continue-btn/);
assert.match(appJs, /document\.getElementById\('flip-cancel-print-btn'\)\?\.addEventListener\('click', \(\) => this\._cancelCurrentPrintJob\(\)\);/);
assert.doesNotMatch(appJs, /complete-print-btn/);
assert.doesNotMatch(appJs, /_completeCurrentManualJobFromToolbar/);
assert.match(appJs, /async _cancelCurrentPrintJob\(\)/);
assert.match(appJs, /document\.getElementById\('flip-modal'\)\?\.classList\.add\('hidden'\);/);
assert.match(viJs, /cancelFromFlip:\s*'[^']+'/);
assert.match(enJs, /cancelFromFlip:\s*'[^']+'/);
assert.doesNotMatch(viJs, /autoTimer:/);
assert.doesNotMatch(enJs, /autoTimer:/);

assert.doesNotMatch(appJs, /Phase2RecoveryModule\.openCheck\(\)/);
assert.doesNotMatch(appJs, /phase2-recovery-good'\)\?\.addEventListener/);
assert.doesNotMatch(appJs, /_completionReady/);
assert.doesNotMatch(continuePrintBlock, /dataset\.mode = 'phase2-review'/);
assert.match(continuePrintBlock, /this\._setPrintButtonIdle\(btn\)/);
assert.match(appJs, /jobStates \|\| result\.JobStates/);
assert.match(appJs, /AppState\.recoveryJobs\.find/);
assert.match(appJs, /async refreshRecoveryContext\(/);
assert.match(appJs, /\/print\/recovery-context/);
assert.match(appJs, /AppState\.recoveryContext/);
assert.match(appJs, /_recoverableJob\(\)/);
assert.doesNotMatch(appJs, /reset\(\)\s*\{[\s\S]*this\.recoveryContext\s*=\s*null;[\s\S]*this\.pendingPrintQueue/);
assert.match(continuePrintBlock, /else\s*\{\s*\/\/ BUG-2 fix:[\s\S]*await this\.refreshRecoveryContext\(\);/);
assert.match(continuePrintBlock, /catch \(err\)\s*\{[\s\S]*await this\.refreshRecoveryContext\(\);/);
assert.doesNotMatch(continuePrintBlock, /catch \(err\)\s*\{[\s\S]*AppState\.recoveryContext\s*=\s*null;/);
assert.doesNotMatch(viJs, /completeMain:/);
assert.doesNotMatch(enJs, /completeMain:/);
assert.doesNotMatch(viJs, /Hoàn tất lệnh in/);
assert.doesNotMatch(enJs, /Complete print job|Finish print job/);
assert.doesNotMatch(viJs, /bước kiểm tra sau mặt sau|trước khi hoàn tất|không cứu lỗi theo từng tờ/);
assert.doesNotMatch(enJs, /post-back-pass review step|before finishing|per-sheet recovery is not available/);
assert.match(viJs, /Nếu không có lỗi, bạn không cần bấm thêm nút nào/);
assert.match(enJs, /If nothing is wrong, no extra button is required/);
assert.match(viJs, /chèn trang trắng/);
assert.match(enJs, /insert a blank page/);
assert.match(viJs, /chọn đúng bản copy/);
assert.match(enJs, /select the correct copy/);
